
version: '3'
services:
  bd:
    build:
      context: ../Banco-IT_Talent/
      # image: desafio_it_talent_junho_01

    container_name: bd
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
